
# Radio Mode: "simple" (9 frequencies, grid GUI) or "slider" (up to 1024 frequencies, slider GUI)
radioMode: simple

# Maximum frequencies (used in slider mode, max 1024)
maxFrequencies: 128

# Simple mode uses exactly 9 frequencies
simpleFrequencies: 9

# Operator and speaker radius in blocks
operatorRadius: 30
speakerRadius: 30

# Base block type for radios
baseBlock: BARREL

# Allow radio item to drop when broken
allowItemDropOnBreak: true

# Admin settings
admin:
  # Show coordinates in frequency overview and /radio list (default: false for privacy)
  showCoordinates: false

# Dimension-specific settings
dimensions:
  enabled: true
  # If true, radios only work within their placed dimension
  restrictToDimension: true

# Sound effects
sounds:
  enabled: true
  frequencyChange: BLOCK_NOTE_BLOCK_PLING
  enable: BLOCK_BEACON_ACTIVATE
  disable: BLOCK_BEACON_DEACTIVATE
  error: ENTITY_VILLAGER_NO
  click: UI_BUTTON_CLICK

# Crafting recipe
crafting:
  enabled: false
  customModelData: 123456
  recipe:
    shape: [ "RCR", "LEL", "ASA" ]
    ingredients:
      R: REDSTONE_BLOCK
      C: COPPER_BLOCK
      L: LODESTONE
      E: ECHO_SHARD
      A: AMETHYST_SHARD
      S: SCULK_SENSOR

# Messages (MiniMessage format)
messages:
  freq_in_use: "<red>Frequency {freq} is already in use.</red>"
  enabled: "<green>Radio enabled on frequency <yellow>{freq}</yellow>.</green>"
  disabled: "<yellow>Radio disabled: <gold>{reason}</gold>.</yellow>"
  mode_changed: "<gold>Radio mode changed to <yellow>{mode}</yellow> (<yellow>{maxFreq}</yellow> frequencies). All out-of-range radios have been disabled.</gold>"
  dimension_mismatch: "<red>This radio is bound to the <yellow>{dimension}</yellow>. You are in <yellow>{current}</yellow>.</red>"
  freq_out_of_range: "<red>Frequency <yellow>{freq}</yellow> is out of range. Switch to slider mode for more frequencies.</red>"
  operator_info: "<gray>Radio Operator: <yellow>{operator}</yellow></gray><newline/><gray>Status: <yellow>{status}</yellow></gray>"
  no_operator: "<gray>This radio is currently <red>inactive</red>.</gray><newline/><gray>No operator assigned.</gray>"


speakerRadius: 30

# Debug logging
debug:
  enabled: false

# Voice chat integration
voice:
  mute_direct: false

  # Interference / static settings
  interference:
    enabled: true
    farDistance: 2000.0     # where noise plateaus
    maxNoiseDb: -18.0       # peak noise loudness at/after farDistance (negative dBFS)

  # SVC sample rate (48k by default)
  sampleRate: 48000
